title = 'Ethan Robert'
theme = 'rusty-typewriter'
themesdir = 'themes'

defaultContentLanguage = 'fr'
languageCode = 'fr'
enableRobotsTXT = true



# rtwt = Rusty Typewriter Theme
[params.rtwt.side.home]
taxonomies = ['tags','series']
countTaxonomy = 3

[taxonomies]
tag = 'tags'
topic = 'topics'
series = 'series'

[params.author]
name = 'Ethan Robert'

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 1


[[menus.main]]
name = 'Portfolio'
url = 'https://x86ethan.github.io'
weight = 2

# build search index ================
[outputFormats]
 [outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "searchindex"
  isPlainText = true
  notAlternative = true

[mediaTypes]
 [mediaTypes."application/json"]
  suffixes = ["json"]

[outputs]
 home = ["HTML","RSS","SearchIndex"]
# ===================================

## Favicon 
[params.meta]
  favicon = true
  faviconVersion = "1"